apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=574155439588.dkr.ecr.ap-south-1.amazonaws.com/testimage          #Write repository name
    argocd-image-updater.argoproj.io/write-back-method: ext:/scripts/auth1.sh            #Setting git credential
    argocd-image-updater.argoproj.io/git-branch: main                                          #git branch where your workflow exists
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: test-
  source:
    repoURL: https://github.com/cmreddyv/argocd_testimage.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://chinni-dns-c4c5e411.hcp.eastus.azmk8s.io:443
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
