apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: testkube-tests
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/cmreddyv/argocd_testimage.git
   targetRevision: HEAD
   path: bd-fusion-dev/sample-moneyin-orchestrator
   plugin:
     name: testkube
 destination:
   server: https://kubernetes.default.svc
   namespace: testkube
